namespace Cu1uSFX
{
    // DO NOT EDIT - this file is automatically generated by SFXList_Editor as you define sounds in the SFX List asset. Changes made here will be overwritten.
    public enum SFX
    {
        None = 0,
        stinky
    }
}
